language: bash
services: docker

env:
  matrix:
  - VERSION=oracle-java-6/xenial
  - VERSION=oracle-java-6/wheezy
  - VERSION=oracle-java-6/trusty
  - VERSION=oracle-java-6/stretch
  - VERSION=oracle-java-6/sid
  - VERSION=oracle-java-6/jessie
  - VERSION=openjdk-8/xenial
  - VERSION=openjdk-8/trusty
  - VERSION=openjdk-8/stretch
  - VERSION=openjdk-8/sid
  - VERSION=openjdk-8/jessie
  - VERSION=openjdk-8/cosmic
  - VERSION=openjdk-8/buster
  - VERSION=openjdk-8/bionic
  - VERSION=openjdk-8/artful
  - VERSION=openjdk-7/xenial
  - VERSION=openjdk-7/wheezy
  - VERSION=openjdk-7/trusty
  - VERSION=openjdk-7/jessie

matrix:
  fast_finish: true
  allow_failures:

branches:
  only:
  - master

before_script:
  - cd "${VERSION}"
  - image="${TRAVIS_REPO_SLUG%%/*}/android-pdk:${VERSION##*/}-${VERSION%%/*}";

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
